import { ImageRequireSource } from "react-native/types";

export const homeIcon: ImageRequireSource = require("../assets/icons/home/home.png");
export const arrowBack: ImageRequireSource = require("../assets/icons/back-arrow/Vector.png");
export const notificationIcon: ImageRequireSource = require("../assets/icons/notification/bell-01.png");
export const eventIcon: ImageRequireSource = require("../assets/icons/event/event-icon.png");
export const profileIcon: ImageRequireSource = require("../assets/icons/profile/Group.png");
export const arrowRight: ImageRequireSource = require("../assets/icons/back-arrow/right/arrow-right.png");
export const dateArrowRight: ImageRequireSource = require("../assets/icons/calendar/arrow-right/right.png");
export const dateArrowLeft: ImageRequireSource = require("../assets/icons/calendar/arrow-left/left.png");
export const addEvent: ImageRequireSource = require("../assets/icons/add-event/Add.png");
export const cameraIcon: ImageRequireSource = require("../assets/icons/camera/camera-01.png");
export const editIcon: ImageRequireSource = require("../assets/icons/edit/Vector.png");
export const circleIcon: ImageRequireSource = require("../assets/icons/circle/circle.png");
export const onlineIcon: ImageRequireSource = require("../assets/icons/event/online/Vector.png");
export const offlineIcon: ImageRequireSource = require("../assets/icons/event/offline/Vector.png");
export const dropdownIcon: ImageRequireSource = require("../assets/icons/dropdown/Polygon.png");
export const checkCircle: ImageRequireSource = require("../assets/icons/checkCircle/circle.png");
export const searchIcon: ImageRequireSource = require("../assets/icons/search/Vector.png");
